# Generated by Django 4.2.3 on 2023-08-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=122)),
                ('post_content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
