# Generated by Django 4.2.3 on 2023-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='title',
            field=models.CharField(default='', max_length=122),
        ),
    ]
