# Generated by Django 4.2.3 on 2023-08-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
    ]
